import './noData.png'
import './icon/earth1.svg'
import './icon/earth2.svg'
import './icon/test.svg'
import './icon/foot.svg'
import './icon/block1.svg'
import './icon/block2.svg'
import './icon/block3.svg'
